### ISSUE TITLE
Removal of Native Debug extension on Linux as a hard dependency

### ISSUE THREAD

**Issue by ghost** [ianic/zig-language-extras#9]
Is there really a reason why the Native Debug extension is required ? lldb seems to be working quite fine on Linux.

**Comment by ianic** [comment]
Uf, really don't know. 
Must say that I'm not using vscode (and this extension) any more.

**Comment by ghost** [comment]
Ahh, ok. It was just something I noted from my usage. I have nothing to add because I don't know the edge cases or the intricacies of Native Debug but in case it was added just because at the time lldb wasn't working on Linux then I think it can safely be removed.
